security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        public_api:
            pattern: ^/api/calculate
            stateless: true
            jwt: ~  # Add this to ensure the JWT token is processed
            security: false  # Allow anonymous access without security

        api:
            pattern: ^/api
            stateless: true
            jwt: ~  # Use JWT for authentication

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/calculate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/vehicle-types, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
